import {
  chmodSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { delimiter, dirname, join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { describe, expect, it } from 'vitest';

const repoRoot = resolve(__dirname, '../../..');
const i18nOutputPath = join('packages', 'desktop', 'src', 'renderer', 'services', 'i18n', 'i18n-keys.d.ts');
const expectedRawI18nOutput = `/* eslint-disable */
/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-i18n-types.js
 */

export type I18nKey =
  | 'common.greeting';

export type I18nModule =
  | 'common';
`;

function writeFixtureFile(root: string, relativePath: string, content: string): void {
  const target = join(root, relativePath);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, content, 'utf8');
}

function createBuildScriptFixture(options: { includeReferenceModule?: boolean } = {}): string {
  const root = mkdtempSync(join(tmpdir(), 'weprompt-postinstall-fixture-'));
  const includeReferenceModule = options.includeReferenceModule ?? true;

  writeFixtureFile(
    root,
    'package.json',
    `${JSON.stringify(
      {
        scripts: { 'i18n:types': 'node scripts/generate-i18n-types.js' },
        devDependencies: { electron: '37.10.3' },
      },
      null,
      2
    )}\n`
  );
  writeFixtureFile(
    root,
    join('packages', 'desktop', 'src', 'common', 'config', 'i18n-config.json'),
    `${JSON.stringify({ referenceLanguage: 'en-US', modules: ['common'] }, null, 2)}\n`
  );

  if (includeReferenceModule) {
    writeFixtureFile(
      root,
      join('packages', 'desktop', 'src', 'renderer', 'services', 'i18n', 'locales', 'en-US', 'common.json'),
      `${JSON.stringify({ greeting: 'Hello' }, null, 2)}\n`
    );
  }

  mkdirSync(join(root, 'scripts'), { recursive: true });
  copyFileSync(join(repoRoot, 'scripts', 'generate-i18n-types.js'), join(root, 'scripts', 'generate-i18n-types.js'));
  copyFileSync(join(repoRoot, 'scripts', 'postinstall.js'), join(root, 'scripts', 'postinstall.js'));
  copyFileSync(join(repoRoot, 'justfile'), join(root, 'justfile'));
  return root;
}

function readJustRecipeCommands(root: string, recipeName: string): string[] {
  const lines = readFileSync(join(root, 'justfile'), 'utf8').split(/\r?\n/);
  const recipeStart = lines.findIndex((line) => line === `${recipeName}:`);
  if (recipeStart === -1) {
    return [];
  }

  const commands: string[] = [];
  for (const line of lines.slice(recipeStart + 1)) {
    if (!line.startsWith('    ')) {
      break;
    }
    commands.push(line.trim());
  }
  return commands;
}

function installFailingBunx(binDir: string): void {
  if (process.platform === 'win32') {
    writeFileSync(join(binDir, 'bunx.cmd'), '@exit /b 23\r\n', 'utf8');
    return;
  }

  const executable = join(binDir, 'bunx');
  writeFileSync(executable, '#!/bin/sh\nexit 23\n', 'utf8');
  chmodSync(executable, 0o755);
}

function installRecordingBunx(binDir: string): void {
  if (process.platform === 'win32') {
    writeFileSync(join(binDir, 'bunx.cmd'), '@echo invoked>"%WEPROMPT_TEST_BUNX_MARKER%"\r\n@exit /b 23\r\n', 'utf8');
    return;
  }

  const executable = join(binDir, 'bunx');
  writeFileSync(executable, '#!/bin/sh\nprintf invoked > "$WEPROMPT_TEST_BUNX_MARKER"\nexit 23\n', 'utf8');
  chmodSync(executable, 0o755);
}

function writeTscBoundaryScript(root: string): string {
  const scriptPath = join(root, 'assert-tsc-boundary.cjs');
  writeFileSync(
    scriptPath,
    `const { existsSync, statSync, writeFileSync } = require('node:fs');
const { resolve } = require('node:path');

const [command, ...args] = process.argv.slice(2);
if (command !== 'tsc' || args.length !== 1 || args[0] !== '--noEmit') {
  process.exit(23);
}

const outputFile = resolve(process.cwd(), ${JSON.stringify(i18nOutputPath)});
if (!existsSync(outputFile) || statSync(outputFile).size === 0) {
  process.exit(42);
}

const marker = process.env.WEPROMPT_TEST_TSC_MARKER;
if (!marker) {
  process.exit(23);
}
writeFileSync(marker, 'invoked', 'utf8');
`,
    'utf8'
  );
  return scriptPath;
}

describe('postinstall native dependency policy', () => {
  it('propagates local electron-builder dependency installation failures', () => {
    const fixtureRoot = createBuildScriptFixture();
    const binDir = join(fixtureRoot, 'bin');
    mkdirSync(binDir);
    installFailingBunx(binDir);

    try {
      const result = spawnSync(process.execPath, ['scripts/postinstall.js'], {
        cwd: fixtureRoot,
        encoding: 'utf8',
        env: {
          ...process.env,
          CI: 'false',
          GITHUB_ACTIONS: 'false',
          PATH: `${binDir}${delimiter}${process.env.PATH ?? ''}`,
        },
      });

      expect(result.status).not.toBe(0);
      expect(result.stdout + result.stderr).toContain('Postinstall failed');
    } finally {
      rmSync(fixtureRoot, { recursive: true, force: true });
    }
  });

  it('retains the intentional CI skip', () => {
    const fixtureRoot = createBuildScriptFixture();
    const binDir = join(fixtureRoot, 'bin');
    mkdirSync(binDir);
    installFailingBunx(binDir);

    try {
      const result = spawnSync(process.execPath, ['scripts/postinstall.js'], {
        cwd: fixtureRoot,
        encoding: 'utf8',
        env: {
          ...process.env,
          CI: 'true',
          GITHUB_ACTIONS: 'false',
          PATH: `${binDir}${delimiter}${process.env.PATH ?? ''}`,
        },
      });

      expect(result.status).toBe(0);
      expect(result.stdout).toContain('skipping rebuild');
    } finally {
      rmSync(fixtureRoot, { recursive: true, force: true });
    }
  });
});

describe('generated i18n prerequisite policy', () => {
  it('creates a non-empty declaration during a cold CI postinstall', () => {
    const fixtureRoot = createBuildScriptFixture();
    const binDir = join(fixtureRoot, 'bin');
    mkdirSync(binDir);
    installFailingBunx(binDir);

    try {
      const result = spawnSync(process.execPath, ['scripts/postinstall.js'], {
        cwd: fixtureRoot,
        encoding: 'utf8',
        env: {
          ...process.env,
          CI: 'true',
          GITHUB_ACTIONS: 'false',
          PATH: `${binDir}${delimiter}${process.env.PATH ?? ''}`,
        },
      });
      const outputFile = join(fixtureRoot, i18nOutputPath);

      expect(result.status).toBe(0);
      expect(existsSync(outputFile)).toBe(true);
      expect(readFileSync(outputFile, 'utf8').length).toBeGreaterThan(0);
    } finally {
      rmSync(fixtureRoot, { recursive: true, force: true });
    }
  });

  it('propagates i18n generation failures during CI postinstall', () => {
    const fixtureRoot = createBuildScriptFixture({ includeReferenceModule: false });

    try {
      const result = spawnSync(process.execPath, ['scripts/postinstall.js'], {
        cwd: fixtureRoot,
        encoding: 'utf8',
        env: { ...process.env, CI: 'true', GITHUB_ACTIONS: 'false' },
      });

      expect(result.status).not.toBe(0);
      expect(result.stdout + result.stderr).toContain('Postinstall failed');
    } finally {
      rmSync(fixtureRoot, { recursive: true, force: true });
    }
  });

  it('generates the declaration before direct typecheck invokes tsc', () => {
    const fixtureRoot = createBuildScriptFixture();
    const outputFile = join(fixtureRoot, i18nOutputPath);
    const tscMarker = join(fixtureRoot, 'tsc-invoked');
    const tscBoundaryScript = writeTscBoundaryScript(fixtureRoot);

    try {
      const wasCold = !existsSync(outputFile);
      const commands = readJustRecipeCommands(fixtureRoot, 'typecheck');
      const statuses = commands.map((command) => {
        const [executable, ...args] = command.split(/\s+/);
        const isTscBoundary = command === 'bunx tsc --noEmit';
        return spawnSync(
          isTscBoundary ? process.execPath : executable,
          isTscBoundary ? [tscBoundaryScript, ...args] : args,
          {
            cwd: fixtureRoot,
            encoding: 'utf8',
            env: {
              ...process.env,
              WEPROMPT_TEST_TSC_MARKER: tscMarker,
            },
          }
        ).status;
      });

      expect({
        wasCold,
        commands,
        statuses,
        generatedOutput: existsSync(outputFile) ? readFileSync(outputFile, 'utf8') : null,
        reachedTscWithPrerequisite: existsSync(tscMarker),
      }).toEqual({
        wasCold: true,
        commands: ['bun run i18n:types', 'bunx tsc --noEmit'],
        statuses: [0, 0],
        generatedOutput: expectedRawI18nOutput,
        reachedTscWithPrerequisite: true,
      });
    } finally {
      rmSync(fixtureRoot, { recursive: true, force: true });
    }
  });

  it('emits deterministic raw output without invoking an unpinned formatter', () => {
    const fixtureRoot = createBuildScriptFixture();
    const binDir = join(fixtureRoot, 'bin');
    const marker = join(fixtureRoot, 'bunx-invoked');
    mkdirSync(binDir);
    installRecordingBunx(binDir);

    try {
      const result = spawnSync(process.execPath, ['scripts/generate-i18n-types.js'], {
        cwd: fixtureRoot,
        encoding: 'utf8',
        env: {
          ...process.env,
          PATH: `${binDir}${delimiter}${process.env.PATH ?? ''}`,
          WEPROMPT_TEST_BUNX_MARKER: marker,
        },
      });

      expect(result.status).toBe(0);
      expect(readFileSync(join(fixtureRoot, i18nOutputPath), 'utf8')).toBe(expectedRawI18nOutput);
      expect(existsSync(marker)).toBe(false);
    } finally {
      rmSync(fixtureRoot, { recursive: true, force: true });
    }
  });
});
