import path from 'node:path';
import { text, gridX, OUT_DIR } from './lib.mjs';

// ---------------------------------------------------------------------------
// Business Review — navy/amber, Cambria + Calibri, Consolas labels.
// Sandwich structure: dark cover/divider/closing, white content slides.
// ---------------------------------------------------------------------------
const BR = {
  navy: '0B1F3A',
  card: '14294D',
  white: 'FFFFFF',
  amber: 'F2A33C',
  mutedDark: '9DB0C9', // muted on navy
  ink: '1F2933',
  muted: '5B6B82', // muted on white
  panel: 'F5F7FA',
};

const brMarker = (x, y) => ({
  geometry: 'rect',
  x: `${x}cm`,
  y: `${y}cm`,
  width: '0.42cm',
  height: '0.42cm',
  fill: BR.amber,
  line: 'none',
});

const brNumberedRow = (index, y, lead, body, bodyWidth = 17) => [
  {
    geometry: 'ellipse',
    name: `RowNum${index}`,
    x: '1.5cm',
    y: `${y - 0.15}cm`,
    width: '1.7cm',
    height: '1.7cm',
    fill: BR.amber,
    line: 'none',
    text: String(index),
    font: 'Cambria',
    size: 16,
    bold: true,
    color: BR.navy,
    align: 'center',
    valign: 'middle',
  },
  text({
    x: '3.7cm',
    y: `${y - 0.1}cm`,
    width: `${bodyWidth}cm`,
    height: '1.2cm',
    text: lead,
    font: 'Calibri',
    size: 20,
    bold: true,
    color: BR.ink,
  }),
  text({
    x: '3.7cm',
    y: `${y + 1.15}cm`,
    width: `${bodyWidth}cm`,
    height: '1.9cm',
    text: body,
    font: 'Calibri',
    size: 18,
    color: BR.ink,
  }),
];

const brKpi = gridX(4);
const brKpiCard = (i, value, label, delta) => [
  {
    geometry: 'roundRect',
    name: `Kpi${i + 1}`,
    x: `${brKpi.xs[i]}cm`,
    y: '4.2cm',
    width: `${brKpi.width}cm`,
    height: '9cm',
    fill: BR.card,
    line: 'none',
  },
  text({
    x: `${brKpi.xs[i]}cm`,
    y: '5.6cm',
    width: `${brKpi.width}cm`,
    height: '2.6cm',
    text: value,
    font: 'Cambria',
    size: 54,
    bold: true,
    color: BR.white,
    align: 'center',
  }),
  text({
    x: `${brKpi.xs[i]}cm`,
    y: '8.6cm',
    width: `${brKpi.width}cm`,
    height: '1.4cm',
    text: label,
    font: 'Calibri',
    size: 14,
    color: BR.mutedDark,
    align: 'center',
  }),
  text({
    x: `${brKpi.xs[i]}cm`,
    y: '10.4cm',
    width: `${brKpi.width}cm`,
    height: '1cm',
    text: delta,
    font: 'Calibri',
    size: 14,
    bold: true,
    color: BR.amber,
    align: 'center',
  }),
];

const brTitle = (title) =>
  text({
    name: 'Title',
    x: '1.5cm',
    y: '1.1cm',
    width: '30.87cm',
    height: '1.9cm',
    text: title,
    font: 'Cambria',
    size: 36,
    bold: true,
    color: BR.navy,
  });

const businessReview = {
  file: path.join(OUT_DIR, 'business-review.pptx'),
  slides: [
    {
      background: BR.navy,
      shapes: [
        text({
          x: '20cm',
          y: '4.6cm',
          width: '13cm',
          height: '9cm',
          text: 'Q3',
          font: 'Cambria',
          size: 220,
          bold: true,
          color: BR.card,
          align: 'center',
        }),
        text({
          x: '2.5cm',
          y: '6.1cm',
          width: '20cm',
          height: '0.9cm',
          text: 'QUARTERLY BUSINESS REVIEW',
          font: 'Consolas',
          size: 14,
          bold: true,
          color: BR.amber,
        }),
        text({
          name: 'Title',
          x: '2.5cm',
          y: '7.2cm',
          width: '24cm',
          height: '2.6cm',
          text: 'Q3 FY26 Business Review',
          font: 'Cambria',
          size: 44,
          bold: true,
          color: BR.white,
        }),
        text({
          x: '2.5cm',
          y: '10.1cm',
          width: '24cm',
          height: '1.1cm',
          text: 'Acme Corp — Jordan Lee, CFO — 14 October FY26',
          font: 'Calibri',
          size: 18,
          color: BR.mutedDark,
        }),
        brMarker(2.5, 16.9),
        text({
          x: '3.3cm',
          y: '16.62cm',
          width: '20cm',
          height: '1cm',
          text: 'Confidential — prepared for the board',
          font: 'Calibri',
          size: 14,
          color: BR.mutedDark,
        }),
      ],
      notes:
        'Cover. Replace company, quarter, presenter and date. Keep the giant quarter numeral — it is the deck motif.',
    },
    {
      background: BR.white,
      shapes: [
        brTitle('Executive Summary'),
        ...brNumberedRow(
          1,
          4.1,
          'Revenue beat plan by 18%',
          'Enterprise renewals and the EMEA launch drove the beat; NRR held at 118%.'
        ),
        ...brNumberedRow(
          2,
          8.0,
          'Margin expanded 1.9pp',
          'Support automation and infra renegotiation offset the FX headwind.'
        ),
        ...brNumberedRow(
          3,
          11.9,
          'Two decisions requested today',
          'Approve the EMEA headcount plan and the FY27 pricing change (slide 7).'
        ),
        {
          geometry: 'roundRect',
          name: 'HeroCard',
          x: '23cm',
          y: '3.8cm',
          width: '9.37cm',
          height: '12.7cm',
          fill: BR.card,
          line: 'none',
        },
        text({
          x: '23.6cm',
          y: '4.7cm',
          width: '8.2cm',
          height: '0.8cm',
          text: 'QUARTER IN ONE NUMBER',
          font: 'Consolas',
          size: 12,
          bold: true,
          color: BR.amber,
        }),
        text({
          x: '23cm',
          y: '6.6cm',
          width: '9.37cm',
          height: '3cm',
          text: '+18%',
          font: 'Cambria',
          size: 66,
          bold: true,
          color: BR.white,
          align: 'center',
        }),
        text({
          x: '23cm',
          y: '10cm',
          width: '9.37cm',
          height: '0.9cm',
          text: 'Revenue vs plan',
          font: 'Calibri',
          size: 14,
          color: BR.mutedDark,
          align: 'center',
        }),
        text({
          x: '23.6cm',
          y: '11.8cm',
          width: '8.2cm',
          height: '3.6cm',
          text: 'Third consecutive quarter above plan; guidance raised for Q4.',
          font: 'Calibri',
          size: 15,
          color: BR.white,
        }),
      ],
      notes:
        'Lead with the beat, then margin, then the asks. Keep to three points — move detail to the section slides.',
    },
    {
      background: BR.white,
      shapes: [
        brTitle('KPI Scorecard'),
        ...brKpiCard(0, '$84.2', 'Revenue, $M', '+18% vs plan'),
        ...brKpiCard(1, '62.4%', 'Gross margin', '+1.9pp QoQ'),
        ...brKpiCard(2, '118%', 'Net revenue retention', '+3pp YoY'),
        ...brKpiCard(3, '4.2', 'CAC payback, years', '-0.3 vs Q2'),
        brMarker(1.5, 14.6),
        text({
          x: '2.3cm',
          y: '14.3cm',
          width: '29cm',
          height: '2.1cm',
          text: 'Every metric carries a period-over-period delta — replace all four cards with this quarter’s headline numbers.',
          font: 'Calibri',
          size: 18,
          color: BR.ink,
        }),
      ],
      notes: 'Read the cards left to right; flag the watch item verbally rather than adding a fifth card.',
    },
    {
      background: BR.white,
      shapes: [
        brTitle('Revenue vs Plan'),
        {
          geometry: 'roundRect',
          name: 'InsightCard',
          x: '23cm',
          y: '3.6cm',
          width: '9.37cm',
          height: '13.4cm',
          fill: BR.panel,
          line: 'none',
        },
        brMarker(23.6, 4.5),
        text({
          x: '23.6cm',
          y: '5.2cm',
          width: '8.2cm',
          height: '1.1cm',
          text: 'Key insight',
          font: 'Cambria',
          size: 20,
          bold: true,
          color: BR.navy,
        }),
        text({
          x: '23.6cm',
          y: '6.5cm',
          width: '8.2cm',
          height: '9.6cm',
          text: 'EMEA contributed 12pp of the 18pp beat. The gap to plan widened every month of the quarter.',
          font: 'Calibri',
          size: 18,
          color: BR.ink,
        }),
      ],
      charts: [
        {
          chartType: 'column',
          name: 'RevenueChart',
          'series1.name': 'Actual',
          'series1.values': '74,78,81,84.2',
          'series1.color': BR.navy,
          'series2.name': 'Plan',
          'series2.values': '71,74,78,80',
          'series2.color': BR.mutedDark,
          categories: 'Q4,Q1,Q2,Q3',
          title: 'Revenue by quarter, $M',
          x: '1.5cm',
          y: '3.6cm',
          width: '20.5cm',
          height: '13.4cm',
        },
      ],
      notes: 'The chart carries the trend; the card carries the so-what. Replace both with the current quarter’s data.',
    },
    {
      background: BR.white,
      shapes: [
        brTitle('Segment Results'),
        brMarker(1.5, 4.3),
        text({
          x: '2.3cm',
          y: '4.0cm',
          width: '15.7cm',
          height: '1.1cm',
          text: 'Enterprise — $38M, +24%',
          font: 'Calibri',
          size: 20,
          bold: true,
          color: BR.ink,
        }),
        text({
          x: '2.3cm',
          y: '5.2cm',
          width: '15.7cm',
          height: '1.8cm',
          text: 'Driver: multi-year renewals. Action: extend the renewal playbook to mid-market.',
          font: 'Calibri',
          size: 18,
          color: BR.ink,
        }),
        brMarker(1.5, 8.3),
        text({
          x: '2.3cm',
          y: '8.0cm',
          width: '15.7cm',
          height: '1.1cm',
          text: 'Mid-market — $29M, +11%',
          font: 'Calibri',
          size: 20,
          bold: true,
          color: BR.ink,
        }),
        text({
          x: '2.3cm',
          y: '9.2cm',
          width: '15.7cm',
          height: '1.8cm',
          text: 'Driver: pricing change. Action: hold discounting at the 8% ceiling.',
          font: 'Calibri',
          size: 18,
          color: BR.ink,
        }),
        brMarker(1.5, 12.3),
        text({
          x: '2.3cm',
          y: '12.0cm',
          width: '15.7cm',
          height: '1.1cm',
          text: 'SMB — $17M, +4%',
          font: 'Calibri',
          size: 20,
          bold: true,
          color: BR.ink,
        }),
        text({
          x: '2.3cm',
          y: '13.2cm',
          width: '15.7cm',
          height: '1.8cm',
          text: 'Driver: self-serve funnel. Action: decision on paid acquisition in Q4.',
          font: 'Calibri',
          size: 18,
          color: BR.ink,
        }),
      ],
      charts: [
        {
          chartType: 'bar',
          name: 'SegmentChart',
          'series1.name': 'Revenue $M',
          'series1.values': '38,29,17',
          'series1.color': BR.navy,
          categories: 'Enterprise,Mid-market,SMB',
          title: 'Revenue by segment, $M',
          x: '19.4cm',
          y: '3.8cm',
          width: '12.97cm',
          height: '12.8cm',
        },
      ],
      notes:
        'One block per segment: result, driver, action. Duplicate this slide if there are more than three segments.',
    },
    {
      background: BR.navy,
      shapes: [
        text({
          x: '20cm',
          y: '4.6cm',
          width: '13cm',
          height: '9cm',
          text: '02',
          font: 'Cambria',
          size: 220,
          bold: true,
          color: BR.card,
          align: 'center',
        }),
        text({
          x: '2.5cm',
          y: '7.4cm',
          width: '18cm',
          height: '0.9cm',
          text: 'SECTION 02',
          font: 'Consolas',
          size: 14,
          bold: true,
          color: BR.amber,
        }),
        text({
          name: 'Title',
          x: '2.5cm',
          y: '8.5cm',
          width: '20cm',
          height: '2.4cm',
          text: 'Priorities & Outlook',
          font: 'Cambria',
          size: 40,
          bold: true,
          color: BR.white,
        }),
      ],
      notes: 'Divider. One per section; the giant number matches the agenda order.',
    },
    {
      background: BR.white,
      shapes: [
        brTitle('Priorities & Decisions'),
        ...brNumberedRow(
          1,
          4.1,
          'Approve EMEA headcount plan',
          '12 quota-carrying hires in H1; payback modeled at 14 months.',
          21
        ),
        text({
          x: '25.5cm',
          y: '4.0cm',
          width: '6.87cm',
          height: '1.1cm',
          text: 'J. LEE · 30 NOV',
          font: 'Consolas',
          size: 13,
          bold: true,
          color: BR.muted,
          align: 'right',
        }),
        ...brNumberedRow(
          2,
          8.0,
          'FY27 pricing change',
          'Move the SMB tier to usage-based pricing; grandfather current contracts.',
          21
        ),
        text({
          x: '25.5cm',
          y: '7.9cm',
          width: '6.87cm',
          height: '1.1cm',
          text: 'A. KIM · 15 DEC',
          font: 'Consolas',
          size: 13,
          bold: true,
          color: BR.muted,
          align: 'right',
        }),
        ...brNumberedRow(
          3,
          11.9,
          'Support automation phase 2',
          'Extends the margin gain by an estimated 0.8pp in FY27.',
          21
        ),
        text({
          x: '25.5cm',
          y: '11.8cm',
          width: '6.87cm',
          height: '1.1cm',
          text: 'R. SHAH · 31 JAN',
          font: 'Consolas',
          size: 13,
          bold: true,
          color: BR.muted,
          align: 'right',
        }),
      ],
      notes:
        'Max three priorities; each carries an owner and a date. These are the asks — pause here for the decision.',
    },
    {
      background: BR.navy,
      shapes: [
        text({
          name: 'Title',
          x: '2.5cm',
          y: '2.6cm',
          width: '26cm',
          height: '2.3cm',
          text: 'Outlook & Next Steps',
          font: 'Cambria',
          size: 40,
          bold: true,
          color: BR.white,
        }),
        brMarker(2.5, 6.4),
        text({
          x: '3.4cm',
          y: '6.05cm',
          width: '26cm',
          height: '1.5cm',
          text: 'Q4 guidance raised to $88-90M on EMEA momentum.',
          font: 'Calibri',
          size: 20,
          color: BR.white,
        }),
        brMarker(2.5, 8.9),
        text({
          x: '3.4cm',
          y: '8.55cm',
          width: '26cm',
          height: '2.1cm',
          text: 'Watch item: CAC payback trend in SMB — review at the January board.',
          font: 'Calibri',
          size: 20,
          color: BR.white,
        }),
        brMarker(2.5, 11.4),
        text({
          x: '3.4cm',
          y: '11.05cm',
          width: '26cm',
          height: '2.1cm',
          text: 'Decisions logged today circulate within 48 hours with owners and dates.',
          font: 'Calibri',
          size: 20,
          color: BR.white,
        }),
        text({
          x: '2.5cm',
          y: '16.6cm',
          width: '26cm',
          height: '1cm',
          text: 'Prepared by Finance — data as of 30 September',
          font: 'Calibri',
          size: 14,
          color: BR.mutedDark,
        }),
      ],
      notes: 'Close on guidance and the watch item. Confirm the decision log before ending the meeting.',
    },
  ],
};

export default { name: 'business-review', file: businessReview.file, slides: businessReview.slides };
