import path from 'node:path';
import { text, gridX, OUT_DIR } from './lib.mjs';

// ---------------------------------------------------------------------------
// Monthly SteerCo — serif-and-gold executive system. Navy Cambria display
// titles over short gold underline bars, orange Consolas kickers, cream
// panels, red month pills, green status chips. White background everywhere.
// ---------------------------------------------------------------------------
const ST = {
  orange: 'F1592A',
  navy: '122B45',
  gold: 'C9A227',
  cream: 'FBF0E7',
  green: '00A651',
  red: 'D7282F',
  ink: '1F2933',
  muted: '5B6B82',
  peach: 'FDE4D8',
  white: 'FFFFFF',
};

const stKicker = (str, x = 1.5, y = 1.0) =>
  text({
    x: `${x}cm`,
    y: `${y}cm`,
    width: '20cm',
    height: '0.8cm',
    text: str,
    font: 'Consolas',
    size: 13,
    bold: true,
    color: ST.orange,
  });

/** Short gold underline bar — the deck's title signature. */
const stGoldBar = (x, y, width = 3.5) => ({
  geometry: 'rect',
  x: `${x}cm`,
  y: `${y}cm`,
  width: `${width}cm`,
  height: '0.12cm',
  fill: ST.gold,
  line: 'none',
});

const stTitle = (title) => [
  text({
    name: 'Title',
    x: '1.5cm',
    y: '1.1cm',
    width: '30.87cm',
    height: '1.9cm',
    text: title,
    font: 'Cambria',
    size: 36,
    bold: true,
    color: ST.navy,
  }),
  stGoldBar(1.5, 3.05),
];

const stLogoSlot = () =>
  text({
    x: '28.5cm',
    y: '0.8cm',
    width: '3.87cm',
    height: '0.7cm',
    text: '[COMPANY LOGO]',
    font: 'Consolas',
    size: 10,
    color: ST.muted,
    align: 'right',
  });

const stAgendaRow = (index, y, name, description) => [
  text({
    x: '1.5cm',
    y: `${y}cm`,
    width: '2.7cm',
    height: '1.4cm',
    text: `0${index}.`,
    font: 'Cambria',
    size: 28,
    bold: true,
    color: ST.navy,
  }),
  text({
    x: '4.6cm',
    y: `${y + 0.15}cm`,
    width: '26cm',
    height: '1.2cm',
    text: name,
    font: 'Calibri',
    size: 20,
    bold: true,
    color: ST.ink,
  }),
  text({
    x: '4.6cm',
    y: `${y + 1.4}cm`,
    width: '26cm',
    height: '1.1cm',
    text: description,
    font: 'Calibri',
    size: 18,
    color: ST.muted,
  }),
];

const stProgramRow = (index, y, program, chipLabel, chipColor, status) => [
  {
    geometry: 'roundRect',
    name: `Program${index}`,
    x: '1.5cm',
    y: `${y}cm`,
    width: '6.5cm',
    height: '3.4cm',
    fill: ST.navy,
    line: 'none',
  },
  text({
    x: '2.1cm',
    y: `${y + 0.5}cm`,
    width: '5.3cm',
    height: '1.1cm',
    text: program,
    font: 'Calibri',
    size: 16,
    bold: true,
    color: ST.white,
  }),
  {
    geometry: 'roundRect',
    x: '2.1cm',
    y: `${y + 2.0}cm`,
    width: '3.0cm',
    height: '0.9cm',
    fill: chipColor,
    line: 'none',
    text: chipLabel,
    font: 'Calibri',
    size: 12,
    bold: true,
    color: ST.white,
    align: 'center',
    valign: 'middle',
  },
  text({
    x: '8.8cm',
    y: `${y + 0.5}cm`,
    width: '13.8cm',
    height: '2.6cm',
    text: status,
    font: 'Calibri',
    size: 18,
    color: ST.ink,
  }),
];

const stCheckRow = (y, label) => [
  {
    geometry: 'roundRect',
    x: '24.6cm',
    y: `${y}cm`,
    width: '0.8cm',
    height: '0.8cm',
    fill: ST.green,
    line: 'none',
    text: '✓',
    font: 'Calibri',
    size: 12,
    bold: true,
    color: ST.white,
    align: 'center',
    valign: 'middle',
  },
  text({
    x: '25.7cm',
    y: `${y - 0.05}cm`,
    width: '6.3cm',
    height: '1.6cm',
    text: label,
    font: 'Calibri',
    size: 15,
    color: ST.ink,
  }),
];

const stPills = gridX(5);
const stMonthPill = (i, month) => ({
  geometry: 'roundRect',
  x: `${stPills.xs[i]}cm`,
  y: '5.6cm',
  width: `${stPills.width}cm`,
  height: '1.2cm',
  fill: ST.red,
  line: 'none',
  text: month,
  font: 'Calibri',
  size: 14,
  bold: true,
  color: ST.white,
  align: 'center',
  valign: 'middle',
});

const stPhaseBar = (startPill, endPill, y, label) => [
  {
    geometry: 'roundRect',
    x: `${stPills.xs[startPill]}cm`,
    y: `${y}cm`,
    width: `${Math.round((stPills.xs[endPill] + stPills.width - stPills.xs[startPill]) * 100) / 100}cm`,
    height: '1.5cm',
    fill: ST.cream,
    line: 'none',
  },
  text({
    x: `${stPills.xs[startPill] + 0.6}cm`,
    y: `${y}cm`,
    width: `${Math.round((stPills.xs[endPill] + stPills.width - stPills.xs[startPill] - 1.2) * 100) / 100}cm`,
    height: '1.5cm',
    text: label,
    font: 'Calibri',
    size: 14,
    color: ST.ink,
    valign: 'middle',
  }),
];

const stCards = gridX(3);
const stDecisionCard = (i, number, title, gap, proposal) => [
  {
    geometry: 'roundRect',
    name: `Decision${i + 1}`,
    x: `${stCards.xs[i]}cm`,
    y: '4.2cm',
    width: `${stCards.width}cm`,
    height: '12.8cm',
    fill: ST.white,
    line: ST.muted,
  },
  text({
    x: `${stCards.xs[i] + 0.8}cm`,
    y: '5.1cm',
    width: `${stCards.width - 1.6}cm`,
    height: '1.1cm',
    text: number,
    font: 'Cambria',
    size: 20,
    bold: true,
    color: ST.navy,
  }),
  text({
    x: `${stCards.xs[i] + 0.8}cm`,
    y: '6.4cm',
    width: `${stCards.width - 1.6}cm`,
    height: '1.1cm',
    text: title,
    font: 'Calibri',
    size: 18,
    bold: true,
    color: ST.ink,
  }),
  text({
    x: `${stCards.xs[i] + 0.8}cm`,
    y: '8.3cm',
    width: `${stCards.width - 1.6}cm`,
    height: '0.8cm',
    text: 'GAP',
    font: 'Consolas',
    size: 12,
    bold: true,
    color: ST.red,
  }),
  text({
    x: `${stCards.xs[i] + 0.8}cm`,
    y: '9.2cm',
    width: `${stCards.width - 1.6}cm`,
    height: '2.4cm',
    text: gap,
    font: 'Calibri',
    size: 14,
    color: ST.ink,
  }),
  text({
    x: `${stCards.xs[i] + 0.8}cm`,
    y: '12.1cm',
    width: `${stCards.width - 1.6}cm`,
    height: '0.8cm',
    text: 'PROPOSAL',
    font: 'Consolas',
    size: 12,
    bold: true,
    color: ST.green,
  }),
  text({
    x: `${stCards.xs[i] + 0.8}cm`,
    y: '13.0cm',
    width: `${stCards.width - 1.6}cm`,
    height: '2.8cm',
    text: proposal,
    font: 'Calibri',
    size: 14,
    color: ST.ink,
  }),
];

const stNextRow = (index, y, label, lead, ownerDate) => [
  {
    geometry: 'ellipse',
    name: `StepNum${index}`,
    x: '1.5cm',
    y: `${y}cm`,
    width: '1.7cm',
    height: '1.7cm',
    fill: ST.green,
    line: 'none',
    text: String(index),
    font: 'Cambria',
    size: 16,
    bold: true,
    color: ST.white,
    align: 'center',
    valign: 'middle',
  },
  text({
    x: '3.7cm',
    y: `${y - 0.15}cm`,
    width: '10cm',
    height: '0.8cm',
    text: label,
    font: 'Consolas',
    size: 12,
    bold: true,
    color: ST.orange,
  }),
  text({
    x: '3.7cm',
    y: `${y + 0.7}cm`,
    width: '21cm',
    height: '1.4cm',
    text: lead,
    font: 'Calibri',
    size: 20,
    bold: true,
    color: ST.ink,
  }),
  text({
    x: '25.5cm',
    y: `${y + 0.75}cm`,
    width: '6.87cm',
    height: '1.1cm',
    text: ownerDate,
    font: 'Consolas',
    size: 13,
    bold: true,
    color: ST.muted,
    align: 'right',
  }),
];

const stAskRow = (y, statement) => [
  stGoldBar(1.5, y + 0.45, 1.2),
  text({
    x: '3.1cm',
    y: `${y}cm`,
    width: '28.5cm',
    height: '1.6cm',
    text: statement,
    font: 'Calibri',
    size: 20,
    bold: true,
    color: ST.ink,
  }),
];

const monthlySteerco = {
  file: path.join(OUT_DIR, 'monthly-steerco.pptx'),
  slides: [
    {
      background: ST.white,
      shapes: [
        {
          geometry: 'ellipse',
          name: 'PeachCircleLarge',
          x: '25.9cm',
          y: '-6.2cm',
          width: '14cm',
          height: '14cm',
          fill: ST.peach,
          line: 'none',
        },
        {
          geometry: 'ellipse',
          name: 'PeachCircleSmall',
          x: '23.3cm',
          y: '-2.6cm',
          width: '8cm',
          height: '8cm',
          fill: ST.peach,
          line: 'none',
        },
        stLogoSlot(),
        stKicker('TRANSFORMATION OFFICE', 2.5, 5.6),
        text({
          name: 'Title',
          x: '2.5cm',
          y: '6.6cm',
          width: '26cm',
          height: '2.5cm',
          text: 'Monthly SteerCo',
          font: 'Cambria',
          size: 44,
          bold: true,
          color: ST.navy,
        }),
        stGoldBar(2.5, 9.15),
        text({
          x: '2.5cm',
          y: '9.7cm',
          width: '24cm',
          height: '1.2cm',
          text: 'June — [Month, Year]',
          font: 'Calibri',
          size: 20,
          bold: true,
          color: ST.ink,
        }),
        text({
          x: '2.5cm',
          y: '11.1cm',
          width: '24cm',
          height: '1.1cm',
          text: 'Meridian Group · Portfolio Update',
          font: 'Calibri',
          size: 18,
          color: ST.muted,
        }),
      ],
      notes:
        'Cover. Replace the month, year and company line; keep the peach corner circles and the gold bar — they are the deck signature.',
    },
    {
      background: ST.white,
      shapes: [
        ...stTitle('Agenda'),
        ...stAgendaRow(1, 4.8, 'Aurora Program & Platform Update', 'Where the rollout stands and what changed since last month.'),
        ...stAgendaRow(2, 8.9, 'Budget & Vendor Decisions', 'Two approvals needed to keep the second-half plan on schedule.'),
        ...stAgendaRow(3, 13.0, 'Risks and Asks', 'Open risks with owners, and what we need from this committee.'),
      ],
      notes: 'Agenda. Three sections maximum; each number matches a divider slide later in the deck.',
    },
    {
      background: ST.white,
      shapes: [
        stLogoSlot(),
        stKicker('SECTION', 2.5, 3.2),
        text({
          x: '2.3cm',
          y: '4.1cm',
          width: '15cm',
          height: '7.7cm',
          text: '01.',
          font: 'Cambria',
          size: 170,
          bold: true,
          color: ST.navy,
        }),
        stGoldBar(2.5, 12.3),
        text({
          name: 'Title',
          x: '2.5cm',
          y: '12.9cm',
          width: '26cm',
          height: '1.8cm',
          text: 'Aurora Program & Platform Update',
          font: 'Cambria',
          size: 32,
          bold: true,
          color: ST.navy,
        }),
      ],
      notes: 'Section divider. Whitespace is intentional — the giant numeral matches the agenda order.',
    },
    {
      background: ST.white,
      shapes: [
        ...stTitle('Program status — [period]'),
        ...stProgramRow(1, 4.4, 'Aurora Rollout', 'On track', ST.green, 'Rollout live at 68% of sites; wave four starts next week with no open blockers.'),
        ...stProgramRow(2, 8.6, 'Data Platform', 'On track', ST.green, 'Ingestion layer shipped; reporting migration holds to the July cutover date.'),
        ...stProgramRow(3, 12.8, 'Service Desk AI', 'At risk', ST.red, 'Pilot accuracy is below target; the vendor fix lands mid-July — watch item.'),
        {
          geometry: 'roundRect',
          name: 'DeliverablesPanel',
          x: '23.87cm',
          y: '4.4cm',
          width: '8.5cm',
          height: '11.8cm',
          fill: ST.cream,
          line: 'none',
        },
        text({
          x: '24.6cm',
          y: '5.2cm',
          width: '7.1cm',
          height: '0.8cm',
          text: 'KEY DELIVERABLES',
          font: 'Consolas',
          size: 12,
          bold: true,
          color: ST.orange,
        }),
        ...stCheckRow(6.7, 'Wave three go-live completed'),
        ...stCheckRow(9.3, 'Vendor statement of work signed'),
        ...stCheckRow(11.9, 'Data quality dashboard shipped'),
      ],
      notes:
        'Status board. Left rail is one box per program with a chip; keep status lines to one sentence and flag the at-risk item verbally.',
    },
    {
      background: ST.white,
      shapes: [
        ...stTitle('Delivery timeline'),
        stMonthPill(0, 'Feb'),
        stMonthPill(1, 'Mar'),
        stMonthPill(2, 'Apr'),
        stMonthPill(3, 'May'),
        stMonthPill(4, 'Jun'),
        ...stPhaseBar(0, 1, 8.0, 'Design freeze'),
        ...stPhaseBar(1, 3, 10.1, 'Pilot at 3 sites'),
        ...stPhaseBar(3, 4, 12.2, 'Scale to all units'),
        text({
          x: '27.1cm',
          y: '4.35cm',
          width: '5cm',
          height: '0.8cm',
          text: 'WE ARE HERE',
          font: 'Consolas',
          size: 12,
          bold: true,
          color: ST.navy,
          align: 'center',
        }),
        {
          geometry: 'rect',
          name: 'TodayLine',
          x: '29.56cm',
          y: '5.2cm',
          width: '0.08cm',
          height: '9.2cm',
          fill: ST.navy,
          line: 'none',
        },
      ],
      notes:
        'Timeline. Month pills stay fixed; move the phase bars and the WE ARE HERE marker to match the reporting month.',
    },
    {
      background: ST.white,
      shapes: [
        ...stTitle('Decisions requested'),
        ...stDecisionCard(0, '01', 'Vendor renewal', 'Current contract lapses 31 Jul with no fallback coverage for support.', 'Renew for twelve months at the renegotiated rate agreed in June.'),
        ...stDecisionCard(1, '02', 'Scale budget', 'Waves five and six of the rollout are unfunded beyond August.', 'Release the contingency line to fund the remaining rollout waves.'),
        ...stDecisionCard(2, '03', 'Hiring plan', 'Two platform engineering roles have been open since April.', 'Approve backfill through contract-to-hire staffing this quarter.'),
      ],
      notes: 'Decision cards. One decision per card: the gap states the problem, the proposal is the single ask.',
    },
    {
      background: ST.white,
      shapes: [
        ...stTitle('Status and next steps'),
        {
          geometry: 'roundRect',
          name: 'CaveatBanner',
          x: '1.5cm',
          y: '4.2cm',
          width: '30.87cm',
          height: '1.5cm',
          fill: ST.cream,
          line: 'none',
        },
        text({
          x: '2.2cm',
          y: '4.2cm',
          width: '29cm',
          height: '1.5cm',
          text: 'INITIAL RESEARCH — MODEL NOT YET FINALIZED',
          font: 'Calibri',
          size: 14,
          bold: true,
          color: ST.orange,
          valign: 'middle',
        }),
        ...stNextRow(1, 7.6, 'NEXT', 'Alignment meeting with the platform vendor', 'K. Dao · 05 Jul'),
        ...stNextRow(2, 12.0, 'FOR CEO', 'Approve the centralized onboarding budget', 'T. Le · 12 Jul'),
      ],
      notes:
        'Next steps. The banner carries the maturity caveat; each row names one action with a single owner and date.',
    },
    {
      background: ST.white,
      shapes: [
        stLogoSlot(),
        text({
          name: 'Title',
          x: '1.5cm',
          y: '2.6cm',
          width: '28cm',
          height: '2.1cm',
          text: 'Asks of this committee',
          font: 'Cambria',
          size: 36,
          bold: true,
          color: ST.navy,
        }),
        stGoldBar(1.5, 4.75),
        ...stAskRow(7.0, 'Approve the vendor renewal and the scale budget today.'),
        ...stAskRow(9.8, 'Nominate one sponsor per business unit by mid-July.'),
        ...stAskRow(12.6, 'Hold thirty minutes monthly for this steering review.'),
        text({
          x: '1.5cm',
          y: '16.6cm',
          width: '28cm',
          height: '1cm',
          text: 'Prepared by the Transformation Office · [contact]',
          font: 'Calibri',
          size: 14,
          color: ST.muted,
        }),
      ],
      notes: 'Closing. Restate the asks as plain sentences; pause here for the committee decision before ending.',
    },
  ],
};

export default { name: 'monthly-steerco', file: monthlySteerco.file, slides: monthlySteerco.slides };
