import path from 'node:path';
import { text, gridX, OUT_DIR } from './lib.mjs';

// ---------------------------------------------------------------------------
// Project Kickoff — white/graphite with teal, deep-teal cover/divider/closing.
// ---------------------------------------------------------------------------
const PK = {
  deep: '0A4F4E',
  teal: '0E7C7B',
  tint: 'EAF4F3',
  panel: 'F4F6F6',
  ink: '1F2933',
  muted: '7B8794',
  onDeep: 'B9D6D4', // muted on deep teal
  white: 'FFFFFF',
};

const pkTitle = (title) =>
  text({
    name: 'Title',
    x: '1.5cm',
    y: '1.1cm',
    width: '30.87cm',
    height: '1.9cm',
    text: title,
    font: 'Cambria',
    size: 36,
    bold: true,
    color: PK.deep,
  });

const pkCircleRow = (label, y, lead, body, bodyWidth = 17.5) => [
  {
    geometry: 'ellipse',
    x: '1.5cm',
    y: `${y - 0.15}cm`,
    width: '1.7cm',
    height: '1.7cm',
    fill: PK.teal,
    line: 'none',
    text: label,
    font: 'Calibri',
    size: 13,
    bold: true,
    color: PK.white,
    align: 'center',
    valign: 'middle',
  },
  text({
    x: '3.7cm',
    y: `${y - 0.1}cm`,
    width: `${bodyWidth}cm`,
    height: '1.2cm',
    text: lead,
    font: 'Calibri',
    size: 20,
    bold: true,
    color: PK.ink,
  }),
  text({
    x: '3.7cm',
    y: `${y + 1.15}cm`,
    width: `${bodyWidth}cm`,
    height: '1.9cm',
    text: body,
    font: 'Calibri',
    size: 18,
    color: PK.ink,
  }),
];

const pkCols = gridX(2);
const pkPhases = gridX(4);
const pkPhaseBox = (i, name, dates) => [
  {
    geometry: 'roundRect',
    name: `Phase${i + 1}`,
    x: `${pkPhases.xs[i]}cm`,
    y: '6.6cm',
    width: `${pkPhases.width}cm`,
    height: '3.2cm',
    fill: i % 2 === 0 ? PK.teal : PK.tint,
    line: 'none',
    text: name,
    font: 'Calibri',
    size: 20,
    bold: true,
    color: i % 2 === 0 ? PK.white : PK.deep,
    align: 'center',
    valign: 'middle',
  },
  text({
    x: `${pkPhases.xs[i]}cm`,
    y: '10.1cm',
    width: `${pkPhases.width}cm`,
    height: '0.9cm',
    text: dates,
    font: 'Consolas',
    size: 13,
    color: PK.muted,
    align: 'center',
  }),
];

const pkRiskCard = (col, row, risk, mitigation, severity) => {
  const y = row === 0 ? 3.8 : 9.9;
  const x = pkCols.xs[col];
  return [
    {
      geometry: 'roundRect',
      x: `${x}cm`,
      y: `${y}cm`,
      width: `${pkCols.width}cm`,
      height: '5.5cm',
      fill: PK.panel,
      line: 'none',
    },
    text({
      x: `${x + 0.7}cm`,
      y: `${y + 0.6}cm`,
      width: `${pkCols.width - 4.2}cm`,
      height: '1.1cm',
      text: risk,
      font: 'Calibri',
      size: 20,
      bold: true,
      color: PK.deep,
    }),
    text({
      x: `${x + pkCols.width - 3.4}cm`,
      y: `${y + 0.7}cm`,
      width: '2.7cm',
      height: '0.8cm',
      text: severity,
      font: 'Consolas',
      size: 12,
      bold: true,
      color: PK.teal,
      align: 'right',
    }),
    text({
      x: `${x + 0.7}cm`,
      y: `${y + 2}cm`,
      width: `${pkCols.width - 1.4}cm`,
      height: '3.1cm',
      text: mitigation,
      font: 'Calibri',
      size: 18,
      color: PK.ink,
    }),
  ];
};

const projectKickoff = {
  file: path.join(OUT_DIR, 'project-kickoff.pptx'),
  slides: [
    {
      background: PK.deep,
      shapes: [
        {
          geometry: 'ellipse',
          x: '23cm',
          y: '-4cm',
          width: '16cm',
          height: '16cm',
          fill: PK.teal,
          opacity: 0.35,
          line: 'none',
        },
        text({
          x: '2.5cm',
          y: '6.1cm',
          width: '20cm',
          height: '0.9cm',
          text: 'PROJECT KICKOFF',
          font: 'Consolas',
          size: 14,
          bold: true,
          color: PK.onDeep,
        }),
        text({
          name: 'Title',
          x: '2.5cm',
          y: '7.2cm',
          width: '25cm',
          height: '2.6cm',
          text: 'Project Atlas — Kickoff',
          font: 'Cambria',
          size: 44,
          bold: true,
          color: PK.white,
        }),
        text({
          x: '2.5cm',
          y: '10.1cm',
          width: '25cm',
          height: '1.1cm',
          text: 'Sponsor: D. Osei — PM: M. Tran — 3 November FY26',
          font: 'Calibri',
          size: 18,
          color: PK.onDeep,
        }),
        text({
          x: '2.5cm',
          y: '16.62cm',
          width: '22cm',
          height: '1cm',
          text: 'Working session — decisions logged in the project charter',
          font: 'Calibri',
          size: 14,
          color: PK.onDeep,
        }),
      ],
      notes: 'Cover. Replace project, sponsor, PM and date. The bleeding circle is the deck motif — keep it.',
    },
    {
      background: PK.white,
      shapes: [
        pkTitle('Why This Project'),
        ...pkCircleRow(
          '1',
          4.1,
          'The problem',
          'Order handling is manual past 500 units/day; error rate doubled in two quarters.'
        ),
        ...pkCircleRow(
          '2',
          8.0,
          'Cost of waiting',
          'Each quarter of delay adds rework cost and blocks the Q2 retail integration.'
        ),
        ...pkCircleRow(
          '3',
          11.9,
          'The opportunity',
          'Automated flow lifts capacity 4x and unblocks two committed customer launches.'
        ),
      ],
      charts: [
        {
          chartType: 'column',
          name: 'CostChart',
          'series1.name': 'Rework cost $K',
          'series1.values': '120,180,260',
          'series1.color': PK.teal,
          categories: 'Now,+1 qtr,+2 qtrs',
          title: 'Cost of waiting, $K per quarter',
          x: '22.5cm',
          y: '3.8cm',
          width: '9.87cm',
          height: '12.6cm',
        },
      ],
      notes: 'Three beats: problem, cost of doing nothing, opportunity. The chart makes the delay cost concrete.',
    },
    {
      background: PK.white,
      shapes: [
        pkTitle('Scope & Deliverables'),
        {
          geometry: 'roundRect',
          x: `${pkCols.xs[0]}cm`,
          y: '3.8cm',
          width: `${pkCols.width}cm`,
          height: '9.4cm',
          fill: PK.tint,
          line: 'none',
        },
        text({
          x: '2.2cm',
          y: '4.4cm',
          width: '13cm',
          height: '1.1cm',
          text: 'In scope',
          font: 'Cambria',
          size: 20,
          bold: true,
          color: PK.deep,
        }),
        text({
          x: '2.2cm',
          y: '5.7cm',
          width: `${pkCols.width - 1.4}cm`,
          height: '7cm',
          text: 'Order intake automation\nWarehouse hand-off API\nOperator dashboard and alerting\nMigration of the current queue',
          font: 'Calibri',
          size: 18,
          color: PK.ink,
        }),
        {
          geometry: 'roundRect',
          x: `${pkCols.xs[1]}cm`,
          y: '3.8cm',
          width: `${pkCols.width}cm`,
          height: '9.4cm',
          fill: PK.panel,
          line: 'none',
        },
        text({
          x: `${pkCols.xs[1] + 0.7}cm`,
          y: '4.4cm',
          width: '13cm',
          height: '1.1cm',
          text: 'Out of scope',
          font: 'Cambria',
          size: 20,
          bold: true,
          color: PK.muted,
        }),
        text({
          x: `${pkCols.xs[1] + 0.7}cm`,
          y: '5.7cm',
          width: `${pkCols.width - 1.4}cm`,
          height: '7cm',
          text: 'Retail partner integration (Q2 project)\nHardware refresh in the warehouse\nBilling system changes',
          font: 'Calibri',
          size: 18,
          color: PK.ink,
        }),
        text({
          x: '1.5cm',
          y: '14cm',
          width: '30.87cm',
          height: '1.8cm',
          text: 'Every deliverable ships with an acceptance criterion agreed by the sponsor before build starts.',
          font: 'Calibri',
          size: 18,
          color: PK.ink,
        }),
      ],
      notes: 'Read out-of-scope out loud — it prevents the most common kickoff misunderstanding.',
    },
    {
      background: PK.white,
      shapes: [
        pkTitle('Team & Responsibilities'),
        ...pkCircleRow(
          'PM',
          3.9,
          'M. Tran — Project manager',
          'Plan, risks, weekly status. Tie-break on schedule questions.',
          16.5
        ),
        ...pkCircleRow(
          'EN',
          7.2,
          'K. Ibarra — Engineering lead',
          'Architecture and delivery. Tie-break on technical questions.',
          16.5
        ),
        ...pkCircleRow(
          'OP',
          10.5,
          'S. Novak — Operations lead',
          'Process design, operator training, cut-over runbook.',
          16.5
        ),
        ...pkCircleRow(
          'QA',
          13.8,
          'L. Devi — Quality lead',
          'Acceptance tests against the agreed criteria; go/no-go input.',
          16.5
        ),
        {
          geometry: 'roundRect',
          name: 'DecisionCard',
          x: '22.5cm',
          y: '3.8cm',
          width: '9.87cm',
          height: '12.6cm',
          fill: PK.tint,
          line: 'none',
        },
        text({
          x: '23.2cm',
          y: '4.5cm',
          width: '8.5cm',
          height: '1.1cm',
          text: 'Decision rights',
          font: 'Cambria',
          size: 20,
          bold: true,
          color: PK.deep,
        }),
        text({
          x: '23.2cm',
          y: '5.9cm',
          width: '8.5cm',
          height: '9.6cm',
          text: 'Scope changes: sponsor\nSchedule inside the quarter: PM\nTechnical approach: engineering lead\nGo/no-go at cut-over: sponsor + QA',
          font: 'Calibri',
          size: 18,
          color: PK.ink,
        }),
      ],
      notes: 'Names and tie-break rights up front; ambiguity here is where projects slip.',
    },
    {
      background: PK.white,
      shapes: [
        pkTitle('Timeline & Milestones'),
        ...pkPhaseBox(0, 'Discover', 'NOV 3 - NOV 14'),
        ...pkPhaseBox(1, 'Build', 'NOV 17 - JAN 9'),
        ...pkPhaseBox(2, 'Pilot', 'JAN 12 - JAN 30'),
        ...pkPhaseBox(3, 'Roll out', 'FEB 2 - FEB 20'),
        text({
          x: '1.5cm',
          y: '12.6cm',
          width: '30.87cm',
          height: '1.2cm',
          text: 'One milestone per phase — each is a demo, not a document:',
          font: 'Calibri',
          size: 18,
          bold: true,
          color: PK.ink,
        }),
        text({
          x: '1.5cm',
          y: '13.9cm',
          width: '30.87cm',
          height: '3.4cm',
          text: 'Signed process map (Nov 14) · First automated order end-to-end (Jan 9) · Pilot at 20% volume (Jan 30) · Full cut-over (Feb 20)',
          font: 'Calibri',
          size: 18,
          color: PK.ink,
        }),
      ],
      connectors: [
        {
          from: 'SLIDE/shape[@name=Phase1]',
          to: 'SLIDE/shape[@name=Phase2]',
          shape: 'elbow',
          color: PK.muted,
          tailEnd: 'triangle',
        },
        {
          from: 'SLIDE/shape[@name=Phase2]',
          to: 'SLIDE/shape[@name=Phase3]',
          shape: 'elbow',
          color: PK.muted,
          tailEnd: 'triangle',
        },
        {
          from: 'SLIDE/shape[@name=Phase3]',
          to: 'SLIDE/shape[@name=Phase4]',
          shape: 'elbow',
          color: PK.muted,
          tailEnd: 'triangle',
        },
      ],
      notes: 'Phases with dates, milestones as demos. Duplicate a phase box if the project has five phases.',
    },
    {
      background: PK.deep,
      shapes: [
        text({
          x: '20cm',
          y: '4.6cm',
          width: '13cm',
          height: '9cm',
          text: '02',
          font: 'Cambria',
          size: 220,
          bold: true,
          color: PK.teal,
          align: 'center',
        }),
        text({
          x: '2.5cm',
          y: '7.4cm',
          width: '18cm',
          height: '0.9cm',
          text: 'SECTION 02',
          font: 'Consolas',
          size: 14,
          bold: true,
          color: PK.onDeep,
        }),
        text({
          name: 'Title',
          x: '2.5cm',
          y: '8.5cm',
          width: '22cm',
          height: '2.4cm',
          text: 'Execution & Governance',
          font: 'Cambria',
          size: 40,
          bold: true,
          color: PK.white,
        }),
      ],
      notes: 'Divider before the execution details. The giant number matches the agenda order.',
    },
    {
      background: PK.white,
      shapes: [
        pkTitle('Risks & Mitigations'),
        ...pkRiskCard(
          0,
          0,
          'Legacy queue data quality',
          'Sample 1,000 records in week one; budget a cleanup sprint before migration.',
          'HIGH'
        ),
        ...pkRiskCard(
          1,
          0,
          'Operator adoption',
          'Two operators embedded in the pilot; training runbook owned by Operations.',
          'MED'
        ),
        ...pkRiskCard(
          0,
          1,
          'Warehouse API stability',
          'Contract test suite against the staging API from week two.',
          'MED'
        ),
        ...pkRiskCard(
          1,
          1,
          'Holiday freeze overlap',
          'Build phase spans the freeze — pilot start is the buffer, not the deadline.',
          'LOW'
        ),
      ],
      notes: 'Each risk pairs with a mitigation and an owner. Review this grid at every steering meeting.',
    },
    {
      background: PK.deep,
      shapes: [
        text({
          name: 'Title',
          x: '2.5cm',
          y: '2.6cm',
          width: '26cm',
          height: '2.3cm',
          text: 'Next Steps',
          font: 'Cambria',
          size: 40,
          bold: true,
          color: PK.white,
        }),
        text({
          x: '2.5cm',
          y: '6.05cm',
          width: '22cm',
          height: '1.5cm',
          text: 'Confirm the charter and decision rights in writing.',
          font: 'Calibri',
          size: 20,
          color: PK.white,
        }),
        text({
          x: '25cm',
          y: '6.15cm',
          width: '6.87cm',
          height: '1.1cm',
          text: 'SPONSOR · NOV 5',
          font: 'Consolas',
          size: 13,
          bold: true,
          color: PK.onDeep,
          align: 'right',
        }),
        text({
          x: '2.5cm',
          y: '8.55cm',
          width: '22cm',
          height: '1.5cm',
          text: 'Discovery interviews with all four operator shifts.',
          font: 'Calibri',
          size: 20,
          color: PK.white,
        }),
        text({
          x: '25cm',
          y: '8.65cm',
          width: '6.87cm',
          height: '1.1cm',
          text: 'PM · NOV 14',
          font: 'Consolas',
          size: 13,
          bold: true,
          color: PK.onDeep,
          align: 'right',
        }),
        text({
          x: '2.5cm',
          y: '11.05cm',
          width: '22cm',
          height: '1.5cm',
          text: 'Staging access to the warehouse API.',
          font: 'Calibri',
          size: 20,
          color: PK.white,
        }),
        text({
          x: '25cm',
          y: '11.15cm',
          width: '6.87cm',
          height: '1.1cm',
          text: 'ENG · NOV 7',
          font: 'Consolas',
          size: 13,
          bold: true,
          color: PK.onDeep,
          align: 'right',
        }),
        text({
          x: '2.5cm',
          y: '16.6cm',
          width: '26cm',
          height: '1cm',
          text: 'Weekly status every Friday — first steering review 21 November',
          font: 'Calibri',
          size: 14,
          color: PK.onDeep,
        }),
      ],
      notes: 'Every commitment has an owner and a date. Close by confirming the first steering review.',
    },
  ],
};

export default { name: 'project-kickoff', file: projectKickoff.file, slides: projectKickoff.slides };
